// If you decide to use the Arduino Cloud Code Editor 
// then this file should be omitted. 
// Use only with Arduino IDE offline software.

// Code generated by Arduino IoT Cloud.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

// *********************************************************************************
const char THING_ID[] = "place-here-id-number-of-your-thing-from-iot-arduino-cloud";
// *********************************************************************************

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBacklightChange();
void onColorChange();
void onBrightnessChange();

bool backlight;
CloudColor color;
int brightness;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(backlight, READWRITE, ON_CHANGE, onBacklightChange);
  ArduinoCloud.addProperty(color, READWRITE, ON_CHANGE, onColorChange);
  ArduinoCloud.addProperty(brightness, READWRITE, ON_CHANGE, onBrightnessChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
