// If you decide to use the Arduino Cloud Code Editor
// then this file should be omitted.
// Use only with Arduino IDE offline software.

// Code generated by Arduino IoT Cloud.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

// *********************************************************************************
const char THING_ID[] = "place-here-id-number-of-your-thing-from-iot-arduino-cloud";
// *********************************************************************************

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onNixieClockChange();
void onCycleChange();
void onFirstBacklightChange();
void onSecondBacklightChange();

CloudSwitch nixieClock;
CloudSwitch cycle;
CloudColoredLight firstBacklight;
CloudColoredLight secondBacklight;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(nixieClock, READWRITE, ON_CHANGE, onNixieClockChange);
  ArduinoCloud.addProperty(cycle, READWRITE, ON_CHANGE, onCycleChange);
  ArduinoCloud.addProperty(firstBacklight, READWRITE, ON_CHANGE, onFirstBacklightChange, 1);
  ArduinoCloud.addProperty(secondBacklight, READWRITE, ON_CHANGE, onSecondBacklightChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
